Repository playcanvas/supersplat, pull requests merged in 2024-12, with the labels that each got.

#310 Update viewer to PlayCanvas Web Components 0.1.9
  src/splat-serialize.ts
  src/templates/viewer-html-template.ts
Labels: enhancement

#311 Update dependencies
  package-lock.json
  package.json
  src/camera.ts
  src/infinite-grid.ts
  src/outline.ts
  src/scene.ts
  src/shaders/splat-shader.ts
  src/splat.ts
  src/underlay.ts
Labels: enhancement

#312 Fix for inverted camera
  src/camera.ts
Labels: bug

#313 Add spherical harmonics to compressed.ply export
  src/asset-loader.ts
  src/camera.ts
  src/sh-utils.ts
  src/shaders/splat-shader.ts
  src/splat-serialize.ts
Labels: enhancement

#314 Export first camera pose in html viewer
  src/splat-serialize.ts
  src/templates/viewer-html-template.ts
Labels: enhancement

#315 Use camera fov when exporting html viewer
  src/splat-serialize.ts
  src/templates/viewer-html-template.ts
Labels: enhancement

#316 Workaround tonemapping bug in viewer html
  src/templates/viewer-html-template.ts
Labels: bug

#320 Limit output SH bands
  src/file-handler.ts
  src/splat-serialize.ts
Labels: bug, enhancement

#323 Update splat sorting
  src/splat.ts
Labels: enhancement

#326 Use Ctrl+A for select all shortcut
  src/main.ts
  src/ui/shortcuts-popup.ts
Labels: bug

#325 Add missing tooltips
  src/ui/localization.ts
  src/ui/right-toolbar.ts
Labels: enhancement

#328 Quick fix
  src/file-handler.ts
Labels: bug

#333 Viewer export options
  package-lock.json
  package.json
  rollup.config.mjs
  src/file-handler.ts
  src/index.html
  src/splat-serialize.ts
  src/templates/viewer-html-template.ts
  src/ui/editor.ts
  src/ui/localization.ts
  src/ui/popup.ts
  src/ui/scss/colors.scss
  src/ui/scss/style.scss
  src/ui/scss/viewer-export-popup.scss
  src/ui/view-panel.ts
  src/ui/viewer-export-popup.ts
Labels: enhancement

#334 Specify colors by url parameter
  src/asset-loader.ts
  src/camera.ts
  src/env.ts
  src/main.ts
  src/model.ts
  src/scene-config.ts
  src/scene.ts
  src/ui/view-panel.ts
Labels: enhancement

#336 Correct German translation for field of view
  src/ui/localization.ts
Labels: bug

#340 Histogram panel update
  src/ui/data-panel.ts
  src/ui/histogram.ts
Labels: enhancement

#339 Fix for compressed.ply export
  src/splat-serialize.ts
Labels: bug

#341 Tweak some UI naming and shortcuts
  src/main.ts
  src/ui/localization.ts
  src/ui/menu.ts
  src/ui/shortcuts-popup.ts
Labels: enhancement

#342 typo: camara -> camera
  src/templates/viewer-html-template.ts
Labels: bug

#344 Add duplicate/separate
  src/edit-ops.ts
  src/editor.ts
  src/file-handler.ts
  src/splat-serialize.ts
  src/ui/localization.ts
  src/ui/menu.ts
  src/ui/svg/select-duplicate.svg
  src/ui/svg/select-separate.svg
Labels: enhancement

#345 Show selection on the active splat only
  src/outline.ts
  src/selection.ts
  src/splat.ts
Labels: enhancement

#346 Shortcut update for select none
  src/main.ts
  src/ui/menu.ts
  src/ui/shortcuts-popup.ts
Labels: enhancement

#350 Rings mode picker update
  src/camera.ts
  src/editor.ts
  src/shaders/splat-shader.ts
Labels: bug

#351 Duplicate fix
  src/splat-serialize.ts
Labels: bug

#352 Improve outline mode
  src/outline.ts
  src/shaders/outline-shader.ts
  src/shaders/splat-shader.ts
Labels: enhancement

#354 Render grid in ortho view
  src/infinite-grid.ts
  src/shaders/infinite-grid-shader.ts
Labels: bug
