Repository playcanvas/supersplat, pull requests merged in 2025-04, with the labels that each got.

#450 Another build update
  package.json
Labels: bug

#459 Camera animation export fix
  src/ui/publish-settings-dialog.ts
  src/ui/viewer-export-popup.ts
Labels: bug

#466 Update default pivot and camera
  src/file-handler.ts
  src/pivot.ts
  src/ply-sequence.ts
  src/ui/bottom-toolbar.ts
Labels: enhancement

#469 Add saturation control
  src/edit-ops.ts
  src/shaders/splat-shader.ts
  src/splat-serialize.ts
  src/splat.ts
  src/ui/color-panel.ts
  src/ui/localization.ts
Labels: feature request

#473 Transform palette fix
  src/splat-overlay.ts
  src/splat.ts
Labels: bug

#476 Add frame rate to video render
  src/render.ts
  src/ui/localization.ts
  src/ui/video-settings-dialog.ts
Labels: bug

#472 Feature box select tool
  src/box-shape.ts
  src/data-processor.ts
  src/editor.ts
  src/main.ts
  src/shaders/box-shape-shader.ts
  src/shaders/intersection-shader.ts
  src/tools/box-selection.ts
  src/ui/bottom-toolbar.ts
  src/ui/localization.ts
Labels: enhancement

#483 Update engine
  package-lock.json
  package.json
  src/asset-loader.ts
  src/data-processor.ts
  src/file-handler.ts
  src/scene.ts
  src/splat-overlay.ts
  src/splat.ts
Labels: enhancement

#484 Ignore infinities when calculating bound
  src/asset-loader.ts
  src/data-processor.ts
  src/shaders/bound-shader.ts
  src/splat.ts
Labels: bug

#486 Update dependencies
  package-lock.json
  package.json
  src/asset-loader.ts
  src/camera.ts
  src/splat-serialize.ts
  src/splat.ts
  src/ui/histogram.ts
Labels: enhancement
